"""
Django settings for prepcamp project.

Generated by 'django-admin startproject' using Django 4.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

from pathlib import Path
# import pyrebase

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-=a8hou1vcx*1zf+piivl2+*f4tnp@u72!o-0b)x@*rnq5s3d%k'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'base'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'prepcamp.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR/'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'prepcamp.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_URL=[BASE_DIR/'static']

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


import pyrebase
import os
import firebase_admin
from firebase_admin import credentials,firestore


# Config = {
#   "apiKey": "AIzaSyDDBU8CKyWSAHnutcdSHqYDQrxVr01FzNE",
#   "authDomain": "prepcamp-2d11b.firebaseapp.com",
#   "databaseURL": "https://prepcamp-2d11b-default-rtdb.firebaseio.com",
#   "projectId": "prepcamp-2d11b",
#   "storageBucket": "prepcamp-2d11b.appspot.com",
#   "messagingSenderId": "369015653140",
#   "appId": "1:369015653140:web:deca38edc029c0fc19b801"
# }

# json_file_path = os.path.join('./prepcamp-2d11b-firebase-adminsdk-jol63-64d1c726d5.json')
# # C:\Users\vedan\prepcamp\prepcamp-2d11b-firebase-adminsdk-jol63-64d1c726d5.json
# cred = credentials.Certificate(json_file_path)
# firebase_admin.initialize_app(cred)

# firebase = pyrebase.initialize_app(Config)
# auth = firebase.auth()
# db=firestore.client()


Config = {
  "apiKey": "AIzaSyDDBU8CKyWSAHnutcdSHqYDQrxVr01FzNE",
  "authDomain": "prepcamp-2d11b.firebaseapp.com",
  "databaseURL": "https://prepcamp-2d11b-default-rtdb.firebaseio.com",
  "projectId": "prepcamp-2d11b",
  "storageBucket": "prepcamp-2d11b.appspot.com",
  "messagingSenderId": "369015653140",
  "appId": "1:369015653140:web:deca38edc029c0fc19b801"
}
firebase=pyrebase.initialize_app(Config)
auth=firebase.auth()
database=firebase.database()


json_file_path = os.path.join('./prepcamp-2d11b-firebase-adminsdk-jol63-64d1c726d5.json')

cred = credentials.Certificate(json_file_path)
firebase_admin.initialize_app(cred)

firebase = pyrebase.initialize_app(Config)
auth = firebase.auth()
db=firestore.client()
